on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - uses: warjiang/setup-skopeo@v0.1.3
        with:
          version: v1.17.0
      - run: deno install
      - run: deno run --cached-only -A ./main.ts
