on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "46 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - uses: warjiang/setup-skopeo@v0.1.3
        with:
          version: v1.17.0
      - run: deno install
      - run: deno run --cached-only -A ./main.ts
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: actions/attest-build-provenance@v1
        with:
          subject-path: ./dist/wsl-rootfs-docker_*.tar.gz
