on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: docker export $(docker create docker:latest) | gzip > rootfs1.tar.gz
      - run: docker export $(docker create docker:latest) | gzip > rootfs2.tar.gz
      - run: sha256sum *
